package com.meyacom.pcis.policy.bom;
// default package

import java.io.Serializable;
import java.util.Date;


/**
 * AbstractPlyAcctinfoVO generated by MyEclipse Persistence Tools
 */

public class IAbstractAcctinfoVO implements Serializable{


    // Fields    

     private String CAppNo;//C_APP_NO申请单号
     private String CPlyNo;//C_PLY_NO保单号
     private Long NEdrPrjNo;//N_EDR_PRJ_NO批改序号
     private String CEdrNo;//C_EDR_NO批单号
     private String CAcctNme;//C_ACCT_NME账户名,特别约定代码
     private String CAcctNo;//C_ACCT_NO账号,中文名
     private String CBankRelCde;//C_BANK_REL_CDE收款行联行号
     private String CBankPro;//C_BANK_PRO银行省
     private String CBankArea;//C_BANK_AREA银行市
     private String CBankCde;//C_BANK_CDE开户行
     private String CCrtCde;//C_CRT_CDE创建人代码
     private Date TCrtTm;//T_CRT_TM创建时间
     private String CUpdCde;//C_UPD_CDE修改人代码
     private Date TUpdTm;//T_UPD_TM修改时间
     
     //add by chencj at 20120713
     private String CBankCounty;	//C_BANK_COUNTY,银行县
     private String CBankRelTyp;	//C_BANK_REL_TYP,收款银行大类
     private String CBankCnaps;	//C_BANK_CNAPS, CNAPS号
     private String CBankAddr;	//C_BANK_ADDR,开户行地址
     private String CPubPri;	//C_PUB_PRI,对公对私
     private String CSettlementTyp;	//C_SETTLEMENT_TYP,结算方式

    // Constructors

    /** default constructor */
    public IAbstractAcctinfoVO() {
    }
    // Property accessors

    public String getCAppNo() {
        return this.CAppNo;
    }
    
    public void setCAppNo(String CAppNo) {
        this.CAppNo = CAppNo;
    }

    public String getCPlyNo() {
        return this.CPlyNo;
    }
    
    public void setCPlyNo(String CPlyNo) {
        this.CPlyNo = CPlyNo;
    }

    public Long getNEdrPrjNo() {
        return this.NEdrPrjNo;
    }
    
    public void setNEdrPrjNo(Long NEdrPrjNo) {
        this.NEdrPrjNo = NEdrPrjNo;
    }

    public String getCEdrNo() {
        return this.CEdrNo;
    }
    
    public void setCEdrNo(String CEdrNo) {
        this.CEdrNo = CEdrNo;
    }

    public String getCAcctNme() {
        return this.CAcctNme;
    }
    
    public void setCAcctNme(String CAcctNme) {
        this.CAcctNme = CAcctNme;
    }

    public String getCAcctNo() {
        return this.CAcctNo;
    }
    
    public void setCAcctNo(String CAcctNo) {
        this.CAcctNo = CAcctNo;
    }

    public String getCBankRelCde() {
        return this.CBankRelCde;
    }
    
    public void setCBankRelCde(String CBankRelCde) {
        this.CBankRelCde = CBankRelCde;
    }

    public String getCBankPro() {
        return this.CBankPro;
    }
    
    public void setCBankPro(String CBankPro) {
        this.CBankPro = CBankPro;
    }

    public String getCBankArea() {
        return this.CBankArea;
    }
    
    public void setCBankArea(String CBankArea) {
        this.CBankArea = CBankArea;
    }

    public String getCBankCde() {
        return this.CBankCde;
    }
    
    public void setCBankCde(String CBankCde) {
        this.CBankCde = CBankCde;
    }

    public String getCCrtCde() {
        return this.CCrtCde;
    }
    
    public void setCCrtCde(String CCrtCde) {
        this.CCrtCde = CCrtCde;
    }

    public Date getTCrtTm() {
        return this.TCrtTm;
    }
    
    public void setTCrtTm(Date TCrtTm) {
        this.TCrtTm = TCrtTm;
    }

    public String getCUpdCde() {
        return this.CUpdCde;
    }
    
    public void setCUpdCde(String CUpdCde) {
        this.CUpdCde = CUpdCde;
    }

    public Date getTUpdTm() {
        return this.TUpdTm;
    }
    
    public void setTUpdTm(Date TUpdTm) {
        this.TUpdTm = TUpdTm;
    }

	public String getCBankCounty() {
		return CBankCounty;
	}

	public void setCBankCounty(String bankCounty) {
		CBankCounty = bankCounty;
	}

	public String getCBankRelTyp() {
		return CBankRelTyp;
	}

	public void setCBankRelTyp(String bankRelTyp) {
		CBankRelTyp = bankRelTyp;
	}

	public String getCBankCnaps() {
		return CBankCnaps;
	}

	public void setCBankCnaps(String bankCnaps) {
		CBankCnaps = bankCnaps;
	}

	public String getCBankAddr() {
		return CBankAddr;
	}

	public void setCBankAddr(String bankAddr) {
		CBankAddr = bankAddr;
	}

	public String getCPubPri() {
		return CPubPri;
	}
 
	public void setCPubPri(String pubPri) {
		CPubPri = pubPri;
	}

	public String getCSettlementTyp() {
		return CSettlementTyp;
	}

	public void setCSettlementTyp(String settlementTyp) {
		CSettlementTyp = settlementTyp;
	}

}