package com.meyacom.pcis.policy.bom;

import java.io.Serializable;
import java.util.Date;

/**
 * AbstractWebPlyVhlowner generated by MyEclipse Persistence Tools
 */

public class IAbstractVhlownerVO  implements Serializable{

	// Fields

	private String CAppNo;
	private String CPlyNo;
	private Long NEdrPrjNo;
	private String CEdrNo;
	private String COwnerCde;
	private String COwnerNme;
	private String COwnerCls;
	private String CCertfCls;
	private String CCertfCde;
	private String CResidAddr;
	private String CClntAddr;
	private String CZipCde;
	private String CWorkdptKind;
	private String CResvTxt1;
	private String CResvTxt2;
	private String CResvTxt3;
	private String CLatestMrk;
	private Date TUpdTm;
	private String CUpdCde;
	private Date TCrtTm;
	private String CCrtCde;
	private String CSex;//C_SEX 性别
	private Date TBirthday;//T_BIRTHDAY 出生日期,出生年月
	private String CVhlOwnerCate;//车主性质

	
	//
    String CResvTxt11 ;//是否有营业执照
	String CResvTxt12 ;//是否有税务登记号
	Date CResvTxt13 ;//营业执照有效止期
	Date CResvTxt14 ;//税务登记号有效止期
	String CResvTxt15 ;//负责人证件类型
	String CResvTxt16 ;//负责人证件号码
	Date CResvTxt17 ;//负责人证件有效止期
	
	
	
	/** 身份证信息采集相关字段  北京客户身份信息采集需求   add by LiuHuan 2016-4-29  */
    private String CNation;				 //民族
    private String CGivenDpt;			 //签发机构
    private String CAddress;			 //住址
    private Date TCertfBgnDate;			 //身份证有效期起期
    private Date TCertfEndDate;			 //身份证有效期起期
    private String CIdCollectionMachine; //身份证采集器编码
	
    
	// Constructors

	public String getCNation() {
		return CNation;
	}

	public void setCNation(String cNation) {
		CNation = cNation;
	}

	public String getCGivenDpt() {
		return CGivenDpt;
	}

	public void setCGivenDpt(String cGivenDpt) {
		CGivenDpt = cGivenDpt;
	}

	public String getCAddress() {
		return CAddress;
	}

	public void setCAddress(String cAddress) {
		CAddress = cAddress;
	}

	public Date getTCertfBgnDate() {
		return TCertfBgnDate;
	}

	public void setTCertfBgnDate(Date tCertfBgnDate) {
		TCertfBgnDate = tCertfBgnDate;
	}

	public Date getTCertfEndDate() {
		return TCertfEndDate;
	}

	public void setTCertfEndDate(Date tCertfEndDate) {
		TCertfEndDate = tCertfEndDate;
	}


	public String getCIdCollectionMachine() {
		return CIdCollectionMachine;
	}

	public void setCIdCollectionMachine(String cIdCollectionMachine) {
		CIdCollectionMachine = cIdCollectionMachine;
	}

	/** default constructor */
	public IAbstractVhlownerVO() {
	}

	// Property accessors

	public String getCAppNo() {
		return this.CAppNo;
	}

	public String getCResvTxt11() {
		return CResvTxt11;
	}

	public void setCResvTxt11(String cResvTxt11) {
		CResvTxt11 = cResvTxt11;
	}

	public String getCResvTxt12() {
		return CResvTxt12;
	}

	public void setCResvTxt12(String cResvTxt12) {
		CResvTxt12 = cResvTxt12;
	}

	public Date getCResvTxt13() {
		return CResvTxt13;
	}

	public void setCResvTxt13(Date cResvTxt13) {
		CResvTxt13 = cResvTxt13;
	}

	public Date getCResvTxt14() {
		return CResvTxt14;
	}

	public void setCResvTxt14(Date cResvTxt14) {
		CResvTxt14 = cResvTxt14;
	}

	public String getCResvTxt15() {
		return CResvTxt15;
	}

	public void setCResvTxt15(String cResvTxt15) {
		CResvTxt15 = cResvTxt15;
	}

	public String getCResvTxt16() {
		return CResvTxt16;
	}

	public void setCResvTxt16(String cResvTxt16) {
		CResvTxt16 = cResvTxt16;
	}

	public Date getCResvTxt17() {
		return CResvTxt17;
	}

	public void setCResvTxt17(Date cResvTxt17) {
		CResvTxt17 = cResvTxt17;
	}

	public void setCAppNo(String CAppNo) {
		this.CAppNo = CAppNo;
	}

	public String getCPlyNo() {
		return this.CPlyNo;
	}

	public void setCPlyNo(String CPlyNo) {
		this.CPlyNo = CPlyNo;
	}

	public Long getNEdrPrjNo() {
		return this.NEdrPrjNo;
	}

	public void setNEdrPrjNo(Long NEdrPrjNo) {
		this.NEdrPrjNo = NEdrPrjNo;
	}

	public String getCEdrNo() {
		return this.CEdrNo;
	}

	public void setCEdrNo(String CEdrNo) {
		this.CEdrNo = CEdrNo;
	}

	public String getCOwnerCde() {
		return this.COwnerCde;
	}

	public void setCOwnerCde(String COwnerCde) {
		this.COwnerCde = COwnerCde;
	}

	public String getCOwnerNme() {
		return this.COwnerNme;
	}

	public void setCOwnerNme(String COwnerNme) {
		this.COwnerNme = COwnerNme;
	}

	public String getCOwnerCls() {
		return this.COwnerCls;
	}

	public void setCOwnerCls(String COwnerCls) {
		this.COwnerCls = COwnerCls;
	}

	public String getCCertfCls() {
		return this.CCertfCls;
	}

	public void setCCertfCls(String CCertfCls) {
		this.CCertfCls = CCertfCls;
	}

	public String getCCertfCde() {
		return this.CCertfCde;
	}

	public void setCCertfCde(String CCertfCde) {
		this.CCertfCde = CCertfCde;
	}

	public String getCResidAddr() {
		return this.CResidAddr;
	}

	public void setCResidAddr(String CResidAddr) {
		this.CResidAddr = CResidAddr;
	}

	public String getCClntAddr() {
		return this.CClntAddr;
	}

	public void setCClntAddr(String CClntAddr) {
		this.CClntAddr = CClntAddr;
	}

	public String getCZipCde() {
		return this.CZipCde;
	}

	public void setCZipCde(String CZipCde) {
		this.CZipCde = CZipCde;
	}

	public String getCWorkdptKind() {
		return this.CWorkdptKind;
	}

	public void setCWorkdptKind(String CWorkdptKind) {
		this.CWorkdptKind = CWorkdptKind;
	}

	public String getCResvTxt1() {
		return this.CResvTxt1;
	}

	public void setCResvTxt1(String CResvTxt1) {
		this.CResvTxt1 = CResvTxt1;
	}

	public String getCResvTxt2() {
		return this.CResvTxt2;
	}

	public void setCResvTxt2(String CResvTxt2) {
		this.CResvTxt2 = CResvTxt2;
	}

	public String getCResvTxt3() {
		return this.CResvTxt3;
	}

	public void setCResvTxt3(String CResvTxt3) {
		this.CResvTxt3 = CResvTxt3;
	}

	public String getCLatestMrk() {
		return this.CLatestMrk;
	}

	public void setCLatestMrk(String CLatestMrk) {
		this.CLatestMrk = CLatestMrk;
	}

	public Date getTUpdTm() {
		return this.TUpdTm;
	}

	public void setTUpdTm(Date TUpdTm) {
		this.TUpdTm = TUpdTm;
	}

	public String getCUpdCde() {
		return this.CUpdCde;
	}

	public void setCUpdCde(String CUpdCde) {
		this.CUpdCde = CUpdCde;
	}

	public Date getTCrtTm() {
		return this.TCrtTm;
	}

	public void setTCrtTm(Date TCrtTm) {
		this.TCrtTm = TCrtTm;
	}

	public String getCCrtCde() {
		return this.CCrtCde;
	}

	public void setCCrtCde(String CCrtCde) {
		this.CCrtCde = CCrtCde;
	}

	public String getCSex() {
		return CSex;
	}

	public void setCSex(String sex) {
		CSex = sex;
	}

	public Date getTBirthday() {
		return TBirthday;
	}

	public void setTBirthday(Date birthday) {
		TBirthday = birthday;
	}

	public String getCVhlOwnerCate() {
		return CVhlOwnerCate;
	}

	public void setCVhlOwnerCate(String cVhlOwnerCate) {
		CVhlOwnerCate = cVhlOwnerCate;
	}
	

}